Normalize kernels
GPflow/GeometricKernels pull request #101
Opened 2023-08-24 20:29 UTC by stoprightthere

Normalize kernels and feature maps, with a flag to turn off this behaviour.

2023-08-26 15:29 UTC, vabor112 reviewed
Please take a look at my comments.

Beyond them, how about we add normalization tests: for `DiscreteSpectrumSpace` use the space's uniform sampling method to get a bunch of xs and check that the the average of k(x, x) is close to 1. For noncompact, nonuniformly sample xs and check that k(x,x) = 1 for each.

2023-08-26 15:29 UTC, vabor112 commented on tests/spaces/test_graph.py
> +    K_normed_cons = MaternKarhunenLoeveKernel(normed_graph, n, normalize=False)
The "normed" in `K_normed_cons` (that refers to the normalized Laplacian) conflicts somewhat with the `normalize` that refers to the normalization constant. Maybe use something like `K_nlap_cons` instead?

2023-08-26 15:29 UTC, vabor112 commented on geometric_kernels/kernels/feature_maps.py
Shouldn't we add normalization to `deterministic_feature_map_compact` and `random_phase_feature_map_compact` as well?

2023-08-26 15:30 UTC, vabor112 commented
BTW, you intended to drop Python 3.7 support but here it is still present and still causes failed checks.

2023-08-26 16:16 UTC, stoprightthere commented on geometric_kernels/kernels/feature_maps.py
But it's in the kernel?

2023-08-26 16:18 UTC, stoprightthere commented
Not only did I "intend" -- I did drop py3.7, check out the devel branch. Once merged, only py>=3.8 checks will be performed.
Re: tests, valid point.

2023-08-26 16:30 UTC, vabor112 commented on geometric_kernels/kernels/feature_maps.py
IMHO this is confusing from the user experience perspective, let's discuss this

2023-09-07 09:59 UTC, vabor112 requested changes
Pls implement the discussed changes.

2023-09-11 17:08 UTC, merged