Homogenize levels/eigenfunctions terminology
GPflow/GeometricKernels pull request #105
Opened 2023-09-02 20:51 UTC by stoprightthere

2023-09-07 09:58 UTC, vabor112 requested changes

2023-09-07 09:58 UTC, vabor112 commented on geometric_kernels/kernels/geometric_kernels.py
> +    consist of one eigenfunction.
Maybe
-  "and eigenfunctions of the Laplace-Beltrami operator" -> " and eigenfunctions of the Laplace-Beltrami operator :math:`\Delta` such that :math:`\Delta \phi_{ij} = \lambda_i \phi_{ij}`".
- " We refer to sets of :math:`\{\phi_{ij}\}_{j=0}^{K_i}` as "levels". In many practical spaces, like the sphere, we can employ _addition theorems_ to efficiently compute the sums over levels :math:`\sum_{j=0}^{K_i} \phi_{ij}(x) \phi_{ij}(x')`. A level may consist of one eigenfunction."
  ->
   "We refer to the pairs :math:`(\lambda_i, G_i(\cdot, \cdot')` where :math:`G_i(\cdot, \cdot') = \sum_{j=0}^{K_i} \phi_{ij}(\cdot) \phi_{ij}(\cdot')` as "levels". For many spaces, like the sphere, we can employ _addition theorems_ to efficiently compute :math:`G_i(\cdot, \cdot')` without calculating the individual :math:`\phi_{ij}`. Note that although  :math:`\phi_{ij}` are guaranteed to correspond to the same eigenvalue :math:`\lambda_i`, the meaning of :math:`K_i` can vary, it does not have to be equal to the dimension of the whole eigenspace corresponding to :math:`\lambda_i`. For example, for `Graph` and `Mesh` it is always equal to 1 with eigenvalues having multiplicity greater than one giving rise to multiple levels with equal :math:`\lambda_i` but different :math:`G_i(\cdot, \cdot')`.".

2023-09-07 09:58 UTC, vabor112 commented on geometric_kernels/kernels/geometric_kernels.py
> +        :param num_levels: number of eigenvalues and levels to include
Maybe "eigenvalues and levels" -> "levels"?

2023-09-07 09:58 UTC, vabor112 commented on geometric_kernels/spaces/base.py
> +        Eigenfunctions of the first `num` levels of the Laplace-Beltrami operator.
"Eigenfunctions of the first `num` levels of the Laplace-Beltrami operator." -> "Eigenfunctions of the Laplace-Beltrami operator corresponding to the first `num` levels."

2023-09-07 09:58 UTC, vabor112 commented on geometric_kernels/spaces/base.py
> +        First `num` eigenvalues of the Laplace-Beltrami operator.
With or without repetitions? Or corresponding to the first `num` levels?

2023-09-07 09:58 UTC, vabor112 commented on geometric_kernels/spaces/product.py
> +    def __init__(self, *spaces: DiscreteSpectrumSpace, num_eigenvalues: int = 32):
which ones, unique, with repetitions, or is this actually the number of levels (which is, in general, neither of these)?

2023-09-11 20:32 UTC, stoprightthere commented on geometric_kernels/kernels/geometric_kernels.py
>      eigenfunctions of the Laplace-Beltrami operator and :math:`S(\cdot)` the
```suggestion
    eigenfunctions of the Laplace-Beltrami operator such that :math:`\Delta \phi_{ij} = \lambda_i \phi_{ij}` and :math:`S(\cdot)` the
```

2023-09-20 16:37 UTC, merged